name: doxygen

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: doxygen
        uses: mattnotmitt/doxygen-action@v1
        with:
          doxyfile-path: 'doxygen/vsf_doxygen_en.conf'
      
      - name: test
        run: |
          tree .

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Default Doxyfile build documentation to html directory. 
          # Change the directory if changes in Doxyfile
          publish_dir: English/html
