name: vsf-cmake-actions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  VSF_PATH: ${{github.workspace}}

jobs:
  build:
    # todo: support windows and macos
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        target: [linux, m484, mps2, esp32, esp32s2]

    steps:
    - uses: actions/checkout@v2
   
    - name: update submodules
      run: |
        cd ${{github.workspace}} && \
        git submodule update --init --recursive $(cat .gitmodules | grep path | cut  -d' ' -f3 | grep -v evm) && \
        git submodule update --init source/component/3rd-party/evm/raw
    
    - name: install depends
      run: sudo apt-get install libsdl2-dev ninja-build

    - name: install arm depend if need
      run: |
        [[ "${{matrix.target}}" != "m484" && "${{matrix.target}}" != "mps2" ]] && exit 0
        sudo apt-get install qemu-system-arm gcc-arm-none-eabi 
      
    - name: install esp32 depend if need
      run: |
        [[ "${{matrix.target}}}" != "esp32"* ]] && exit 0
        sudo apt-get install git wget make libncurses-dev flex bison gperf python
        mkdir -p ~/esp
        cd ~/esp
        wget https://dl.espressif.com/dl/xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0.tar.gz
        tar -xzf xtensa-esp32-elf-*
        export PATH="$PATH:$HOME/esp/xtensa-esp32-elf/bin"
    
    - name: configure cmake
      run: cmake -GNinja -S ${SOURCE_PATH} -B ${SOURCE_PATH}/build
      env:
        SOURCE_PATH: ${{github.workspace}}/example/template/project/cmake/${{matrix.target}}

    - name: build
      # Build your program with the given configuration
      run: cmake --build ${SOURCE_PATH}/build
      env:
        SOURCE_PATH: ${{github.workspace}}/example/template/project/cmake/${{matrix.target}}
